Bookstore: initialize project with components
Bornittah/book-store pull request #1
Opened 2022-07-13 18:46 UTC by Bornittah

**Implementation**

- Initialise React app.
- Create a directory for your components.
- Add [React Router](https://reactrouter.com/web/guides/quick-start) and set two <Route>s and <Link>s for the app's navigation:
    - Books - the default view:
        - Should display the list of books (empty at this point but it should be ready for the data) with the Remove button (no funcionality yet).
            - Create a component called Book for displaying a single book (receive a title and an author as prop) and reuse it in a component that displays a list of books.
      - Should have a form for adding a book (no functionality yet).
          - Create form component with inputs for a title and an author 
    - Categories:
        - Should display a button "Check status" only.

2022-07-13 20:46 UTC, DammyShittu requested changes
Hi @Bornittah,

✔️ Use of Links for navbar

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-13 20:46 UTC, DammyShittu commented on src/components/Books.jsx
> +        <Button value="Remove" />
- [ ] This remove button should be in the Book component as that is where the remove event will be triggered and handled. Kindly move it to the component.

2022-07-13 20:46 UTC, DammyShittu commented on src/components/Books.jsx
> +      </li>
- [ ] Let's set up this component to render the Book component with the book data passed in as a prop. See example

  ```
  import Book from './Book';
  import Form from './Form';
  import Button from './shared/Button';
  
  const Books = () => (
    <div>
      <h2>List of Books</h2>
      <ul>
        <li>
          <Book title="first book" author="first author" />
        </li>
  .
  .
  .
  ```

2022-07-13 20:46 UTC, DammyShittu commented on src/components/Book.jsx
> +export default Book;
- [ ] The Book component representing a single book should take in the book data as a prop and render it. Let's do that. Just as we have passed in the title and author as a prop earlier in the Books component, we can then accept the props here and render the title and author. In the end you should have something like this:

  ```
  import PropTypes from 'prop-types';
  import Button from './shared/Button';
  
  const Book = (props) => {
    const { title, author } = props;
    return (
      <div>
        <h2>{title}</h2>
        <ul>
          <li>{author}</li>
        </ul>
        <Button value="remove" />
      </div>
    );
  };
  
  Book.propTypes = {
    title: PropTypes.string.isRequired,
    author: PropTypes.string.isRequired,
  };

  export default Book;
  ```

  **NB:** You may need to install the `prop-types` package for prop validation and type checking

2022-07-14 13:25 UTC, BenMukebo approved these changes
### Hi @Bornittah, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 13:25 UTC, BenMukebo commented on src/components/shared/NavBar.jsx
> +        </li>
- [ OPTIONAL] It is not necessary to have two links in the navbar which lead to the same page "Book page" 🤔  I think you only need to have <Link>s in the navbar which leads to the booklist and categories locations 👍🏻

2022-07-14 13:27 UTC, merged